name: Flazzy Publish

on:
  push:
    paths:
      - '.github/workflows/**'
      - 'Flazzy/**'

# on:
#   push:
#     branches:
#       - master

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'

    - name: Publish on new version
      id: publish_nuget
      uses: alirezanet/publish-nuget@v3.0.4
      with:
        # Filepath of the project to be packaged, relative to root of repository
        PROJECT_FILE_PATH: Flazzy/Flazzy.csproj
        
        # NuGet package id, used for version detection & defaults to project name
        PACKAGE_NAME: UnfamiliarLegacy.Flazzy
        
        # Filepath with version info, relative to root of repository & defaults to PROJECT_FILE_PATH
        VERSION_FILE_PATH: Flazzy/Flazzy.csproj

        # Regex pattern to extract version info in a capturing group
        VERSION_REGEX: ^\s*<Version>(.*)<\/Version>\s*$

        # Flag to toggle git tagging, enabled by default
        TAG_COMMIT: true

        # Format of the git tag, [*] gets replaced with actual version
        TAG_FORMAT: v*

        # API key to authenticate with NuGet server
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}

        # NuGet server uri hosting the packages, defaults to https://api.nuget.org
        NUGET_SOURCE: https://api.nuget.org

        # Flag to toggle pushing symbols along with nuget package to the server, disabled by default
        INCLUDE_SYMBOLS: true